export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/q3jHCb4dMfYF6ojikKuHd6LscxC.jpg",
    id: 84958,
    name: "Loki",
    original_language: "en",
    original_name: "Loki",
    overview:
      "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.",
    poster_path: "/voHUmluYmKyleFkTu3lOXQG702u.jpg",
    media_type: "tv",
    genre_ids: [18, 10765],
    popularity: 3827.66,
    first_air_date: "2021-06-09",
    vote_average: 8.1,
    vote_count: 10561,
    origin_country: ["US"],
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/4N6zEMfZ57zNEQcM8gWeERFupMv.jpg",
    id: 91363,
    name: "What If...?",
    original_language: "en",
    original_name: "What If...?",
    overview:
      "Taking inspiration from the comic books of the same name, each episode explores a pivotal moment from the Marvel Cinematic Universe and turns it on its head, leading the audience into uncharted territory.",
    poster_path: "/lztz5XBMG1x6Y5ubz7CxfPFsAcW.jpg",
    media_type: "tv",
    genre_ids: [16, 10759, 10765],
    popularity: 89.206,
    first_air_date: "2021-08-11",
    vote_average: 8.197,
    vote_count: 3720,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/aTjbqMONy77fHJrIYu14g1F0d5h.jpg",
    id: 88396,
    name: "The Falcon and the Winter Soldier",
    original_language: "en",
    original_name: "The Falcon and the Winter Soldier",
    overview:
      "Following the events of “Avengers: Endgame”, the Falcon, Sam Wilson and the Winter Soldier, Bucky Barnes team up in a global adventure that tests their abilities, and their patience.",
    poster_path: "/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
    media_type: "tv",
    genre_ids: [10759, 18],
    popularity: 82.756,
    first_air_date: "2021-03-19",
    vote_average: 7.686,
    vote_count: 8052,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/1i1N0AVRb54H6ZFPDTwbo9MLxSF.jpg",
    id: 85271,
    name: "WandaVision",
    original_language: "en",
    original_name: "WandaVision",
    overview:
      "Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.",
    poster_path: "/glKDfE6btIRcVB5zrjspRIs4r52.jpg",
    media_type: "tv",
    genre_ids: [10765, 9648, 18],
    popularity: 86.567,
    first_air_date: "2021-01-15",
    vote_average: 8.259,
    vote_count: 11384,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/1R68vl3d5s86JsS2NPjl8UoMqIS.jpg",
    id: 88329,
    name: "Hawkeye",
    original_language: "en",
    original_name: "Hawkeye",
    overview:
      "Former Avenger Clint Barton has a seemingly simple mission: get back to his family for Christmas. Possible? Maybe with the help of Kate Bishop, a 22-year-old archer with dreams of becoming a superhero. The two are forced to work together when a presence from Barton’s past threatens to derail far more than the festive spirit.",
    poster_path: "/ct5pNE5dDHryHLDnxyZPYcqO1sz.jpg",
    media_type: "tv",
    genre_ids: [18, 35, 10759],
    popularity: 128.697,
    first_air_date: "2021-11-24",
    vote_average: 7.942,
    vote_count: 2934,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/2meX1nMdScFOoV4370rqHWKmXhY.jpg",
    id: 93405,
    name: "Squid Game",
    original_language: "ko",
    original_name: "오징어 게임",
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games—with high stakes. But, a tempting prize awaits the victor.",
    poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    media_type: "tv",
    genre_ids: [10759, 9648, 18],
    popularity: 143.18,
    first_air_date: "2021-09-17",
    vote_average: 7.831,
    vote_count: 13144,
    origin_country: ["KR"],
  },
  {
    adult: false,
    backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    id: 1399,
    name: "Game of Thrones",
    original_language: "en",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 662.154,
    first_air_date: "2011-04-17",
    vote_average: 8.442,
    vote_count: 22092,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/rBF8wVQN8hTWHspVZBlI3h7HZJ.jpg",
    id: 60625,
    name: "Rick and Morty",
    original_language: "en",
    original_name: "Rick and Morty",
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    poster_path: "/gdIrmf2DdY5mgN6ycVP0XlzKzbE.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10765, 10759],
    popularity: 1136.444,
    first_air_date: "2013-12-02",
    vote_average: 8.701,
    vote_count: 8755,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
    id: 71446,
    name: "Money Heist",
    original_language: "es",
    original_name: "La Casa de Papel",
    overview:
      "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
    poster_path: "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 97.697,
    first_air_date: "2017-05-02",
    vote_average: 8.256,
    vote_count: 17899,
    origin_country: ["ES"],
  },
  {
    adult: false,
    backdrop_path: "/iq5L971DFW1SwLJdvl7OpPI1QeZ.jpg",
    id: 114868,
    name: "Record of Ragnarok",
    original_language: "ja",
    original_name: "終末のワルキューレ",
    overview:
      "Before eradicating humankind from the world, the gods give them one last chance to prove themselves worthy of survival. Let the Ragnarok battles begin.",
    poster_path: "/kTs2WNZOukpWdNhoRlH94pSJ3xf.jpg",
    media_type: "tv",
    genre_ids: [16, 10759, 10765],
    popularity: 64.147,
    first_air_date: "2021-06-17",
    vote_average: 8.51,
    vote_count: 1517,
    origin_country: ["JP"],
  },
  {
    adult: false,
    backdrop_path: "/9zcbqSxdsRMZWHYtyCd1nXPr2xq.jpg",
    id: 82856,
    name: "The Mandalorian",
    original_language: "en",
    original_name: "The Mandalorian",
    overview:
      "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
    poster_path: "/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759, 18],
    popularity: 158.815,
    first_air_date: "2019-11-12",
    vote_average: 8.5,
    vote_count: 9442,
    origin_country: ["US"],
  },
];
